param(
    [string]$ReleaseRoot = "",
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

# Resolve the repository root. This script may be called from any directory.
function Get-RepoRoot {
    $scriptDir = Split-Path -Parent $PSCommandPath
    return (Resolve-Path (Join-Path $scriptDir "..")).Path
}

# Build the requested Chinese export directory name without relying on source-file encoding.
function Get-DefaultExportFolderName {
    return @([char]0x6700, [char]0x65B0, [char]0x7248, "ccswitchmulti") -join ""
}

# Resolve the final export directory. By default it sits under the LLMservice root.
function Get-ExportRoot {
    param([string]$RepoRoot, [string]$RequestedRoot)

    if (-not [string]::IsNullOrWhiteSpace($RequestedRoot)) {
        return $RequestedRoot
    }

    $workspaceRoot = Split-Path -Parent $RepoRoot
    return Join-Path $workspaceRoot (Get-DefaultExportFolderName)
}

# Copy matched build artifacts and return the copied file count.
function Copy-Artifacts {
    param(
        [string]$Pattern,
        [string]$Destination
    )

    New-Item -ItemType Directory -Force -Path $Destination | Out-Null
    $items = @(Get-ChildItem -Path $Pattern -File -ErrorAction SilentlyContinue)
    foreach ($item in $items) {
        Copy-Item -LiteralPath $item.FullName -Destination (Join-Path $Destination $item.Name) -Force
    }
    return $items.Count
}

# Write a clear note for platforms that cannot be built on the current host.
function Write-PlatformNote {
    param(
        [string]$Path,
        [string]$Platform,
        [string]$Reason
    )

    New-Item -ItemType Directory -Force -Path $Path | Out-Null
    $content = @(
        "# $Platform build note",
        "",
        $Reason,
        "",
        "This directory was generated by scripts/export-latest-ccswitchmulti.ps1.",
        "Build this platform on its native OS, or configure a complete cross-compile toolchain, then run the same export script."
    ) -join "`r`n"
    Set-Content -LiteralPath (Join-Path $Path "BUILD_ON_PLATFORM.md") -Value $content -Encoding UTF8
}

# Write SHA256 checksums for all exported artifacts.
function Write-Checksums {
    param([string]$Root)

    $files = @(Get-ChildItem -Path $Root -Recurse -File | Where-Object { $_.Name -ne "SHA256SUMS.txt" })
    $lines = foreach ($file in $files) {
        $hash = Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256
        $relative = $file.FullName.Substring($Root.Length).TrimStart("\", "/")
        "$($hash.Hash)  $relative"
    }
    Set-Content -LiteralPath (Join-Path $Root "SHA256SUMS.txt") -Value ($lines -join "`r`n") -Encoding UTF8
}

# Write the root release README so testers know which artifact to use.
function Write-ReleaseReadme {
    param(
        [string]$Root,
        [string]$Version
    )

    $content = @(
        "# Latest CCSwitchMulti",
        "",
        "Version: $Version",
        "",
        "Directories:",
        "- windows/installer: Windows installers, including NSIS setup and MSI when available.",
        "- windows/portable: Windows portable zip. Unzip and run the executable.",
        "- windows/raw-exe: Raw Tauri release executable for quick local verification.",
        "- linux and macos: Build notes when this Windows host cannot produce native artifacts.",
        "- SHA256SUMS.txt: SHA256 checksums for exported files.",
        "",
        "Note: the portable build still stores app data under the user's normal system app-data directory."
    ) -join "`r`n"
    Set-Content -LiteralPath (Join-Path $Root "README.md") -Value $content -Encoding UTF8
}

$repoRoot = Get-RepoRoot
$exportRoot = Get-ExportRoot -RepoRoot $repoRoot -RequestedRoot $ReleaseRoot
$tauriDir = Join-Path $repoRoot "src-tauri"
$releaseDir = Join-Path $tauriDir "target\release"
$bundleDir = Join-Path $releaseDir "bundle"
$packageJson = Get-Content -LiteralPath (Join-Path $repoRoot "package.json") -Raw | ConvertFrom-Json
$version = [string]$packageJson.version

if (-not $SkipBuild) {
    Push-Location $repoRoot
    $buildConfig = New-TemporaryFile
    try {
        $override = @{
            bundle = @{
                createUpdaterArtifacts = $false
            }
        } | ConvertTo-Json -Depth 8
        Set-Content -LiteralPath $buildConfig.FullName -Value $override -Encoding UTF8
        pnpm tauri build --bundles nsis --config $buildConfig.FullName
        if ($LASTEXITCODE -ne 0) {
            throw "tauri build failed with exit code $LASTEXITCODE"
        }
    } finally {
        Remove-Item -LiteralPath $buildConfig.FullName -Force -ErrorAction SilentlyContinue
        Pop-Location
    }
}

if (Test-Path -LiteralPath $exportRoot) {
    Remove-Item -LiteralPath $exportRoot -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $exportRoot | Out-Null

$windowsInstaller = Join-Path $exportRoot "windows\installer"
$windowsPortable = Join-Path $exportRoot "windows\portable"
$windowsRawExe = Join-Path $exportRoot "windows\raw-exe"

$currentSetupPattern = Join-Path $bundleDir "nsis\CCSwitchMulti_$version`_x64-setup.exe"
Copy-Artifacts -Pattern $currentSetupPattern -Destination $windowsInstaller | Out-Null
Copy-Artifacts -Pattern (Join-Path $bundleDir "nsis\*.sig") -Destination $windowsInstaller | Out-Null

$sourceExe = Join-Path $releaseDir "cc-switch.exe"
if (Test-Path -LiteralPath $sourceExe) {
    $stage = Join-Path $windowsPortable "CCSwitchMulti_portable_stage"
    New-Item -ItemType Directory -Force -Path $stage | Out-Null
    Copy-Item -LiteralPath $sourceExe -Destination (Join-Path $stage "CCSwitchMulti.exe") -Force
    Compress-Archive -Path (Join-Path $stage "*") -DestinationPath (Join-Path $windowsPortable "CCSwitchMulti_$version`_x64-portable.zip") -Force
    Remove-Item -LiteralPath $stage -Recurse -Force
}

if (Test-Path -LiteralPath $sourceExe) {
    New-Item -ItemType Directory -Force -Path $windowsRawExe | Out-Null
    Copy-Item -LiteralPath $sourceExe -Destination (Join-Path $windowsRawExe "CCSwitchMulti.exe") -Force
}

Write-PlatformNote -Path (Join-Path $exportRoot "linux") -Platform "Linux" -Reason "Run pnpm tauri build on a Linux host with Rust, Node/pnpm, and Tauri WebKit/GTK dependencies installed, then run this export script."
Write-PlatformNote -Path (Join-Path $exportRoot "macos") -Platform "macOS" -Reason "Run pnpm tauri build on a macOS host with Xcode Command Line Tools, Rust, and Node/pnpm installed, then run this export script."
Copy-Item -LiteralPath (Join-Path $exportRoot "linux\BUILD_ON_PLATFORM.md") -Destination (Join-Path $exportRoot "linux-build-note.md") -Force
Copy-Item -LiteralPath (Join-Path $exportRoot "macos\BUILD_ON_PLATFORM.md") -Destination (Join-Path $exportRoot "macos-build-note.md") -Force
Write-ReleaseReadme -Root $exportRoot -Version $version
Write-Checksums -Root $exportRoot

Write-Host "Exported CCSwitchMulti release artifacts to: $exportRoot"
